baseURL: "https://koooommmm.github.io/portfolio/"
languageCode: ja
publishDir: docs
canonifyurls: true
build:
  writeStats: true
params:
  title: kyuki's profile
  author: kyuki
  description: kyuki's profile
  theme:
    mainTheme: dark
    showAttribute: true
    singlePage: false

  profile:
    name: "kyuki"
    location: "Kyoto, JP"
    photo: profile.jpg
  social:
    title: Links
    list:
      - icon: fab fa-github
        url: "https://github.com/koooommmm"
        title: GitHub
      - icon: icon.png
        url: "#"
        title: Note
  showInAccordion:
    - item: aboutme
      expand: true
    - item: experience
    - item: education
    - item: publication
    - item: project
    - item: skill
    - item: hobby
  aboutme:
    title: About Me
    icon: fas fa-user
    description: "京都在住のエンジニア。町屋で暮らしつつゆるーく生きてます。"
  experience:
    title: Experiences
    icon: fas fa-briefcase
    list:
      - dates: 2023 - *現在*
        company: メンバーズ
      - dates: 2020 - 2023
        company: NTTコムウェア
  education:
    title: Education
    icon: fas fa-graduation-cap
    list:
      - degree: Master of Science
        college: 神戸大学大学院システム情報学研究科
        dates: 2018 - 2020
      - degree: Bachelor of Science
        college: 神戸大学工学部情報知能工学科
        dates: 2014 - 2018
  project:
    title: Projects
    icon: fas fa-project-diagram
    list:
      - title: 自治体専用ビジネスチャット/電子申請システムの運用
        description: SREとして環境整備/自動化/SLO策定に従事
      - title: 故障修理支援システム移行
        description: マスタデータ整備やパートナー企業の進捗管理に従事
      - title: ビジネスチャットサービスの運用
        description: SREとして環境整備/デプロイ/障害対応に従事
      - title: 道路点検システム開発
        description: 道路点検AIの精度向上やWebアプリケーション開発に従事
  publication:
    title: Publications
    icon: fas fa-book
    format:
      - date
      - title
      - authors
      - journal
    types:
      - Journal Articles
      - Proceedings
    list:
      - title: >-
          柔軟膜ひずみセンサを用いた嚥下障害リハビリテーションのための喉頭挙上の検出
        date: "2018"
        journal: "計測自動制御学会論文集, Vol.55, No.10, pp. 655-661 (2019-10)."
        url: "https://www.jstage.jst.go.jp/article/sicetr/55/10/55_655/_article/-char/ja/"
        type: Journal Articles
      - title: >-
          柔軟膜ひずみセンサを用いた高齢者に対する嚥下リハビリテーションのための喉頭挙上検出
        date: "2019"
        journal: "第36回センシングフォーラム, 慶應義塾大学矢上キャンパス, 第36回センシングフォーラム資料, p.124 (2019-8)."
        type: Proceedings
      - title: >-
          柔軟膜ひずみセンサを用いたバンド型デバイスによる喉頭挙上の検出
        date: "2019"
        journal: "平成30年度SICE関西支部・ISCIE若手研究発表会, 大阪工業大学梅田キャンパス, 予稿集USB, pp. 164-165 (2019-1)."
        type: Proceedings
      - title: >-
          柔軟膜ひずみセンサを用いた装具デバイスによる喉頭運動の検出
        date: "2018"
        journal: "第19回公益社団法人計測自動制御学会システムインテグレーション部門講演会, 大阪工業大学梅田キャンパス, 予稿集USB, pp. 381-382 (2018-12)."
        type: Proceedings
      - title: >-
          Laryngeal Elevation Detection for Mendelsohn Maneuver by Stretchable Strain Sensors
        date: "2018"
        journal: "40th Annual International Conference of the IEEE Engineering in Medicine and Biology Society (EMBC'18), Hawaii Convention Center, USA, FrPoS-31.19, (2018-7)."
        type: Proceedings
      - title: >-
          柔軟膜ひずみセンサを用いた嚥下障害リハビリテーションのための喉頭挙上及び降下の検出
        date: "2018"
        journal: "第35回センシングフォーラム, pp. 147-152, (2018.8)."
        type: Proceedings
  skill:
    title: Skills
    panelId: skill-panel
    icon: fas fa-cogs
    language:
      - skill: "Python"
        skillrating: 60
      - skill: "JavaScript"
        skillrating: 40
      - skill: "Java"
        skillrating: 20
    frontend:
      - skill: "jQuery"
        skillrating: 20
      - skill: "React"
        skillrating: 10
    backend:
      - skill: "Django"
        skillrating: 50
      - skill: "Express"
        skillrating: 50
    infra:
      - skill: "AWS"
        skillrating: 60
      - skill: "Linux"
        skillrating: 60
      - skill: "Ansible"
        skillrating: 60
      - skill: "Terraform"
        skillrating: 50
